"""200-day AI curriculum: (day, theme, 10 concepts).

Phases
  Days   1- 15  Python & the data toolkit
  Days  16- 34  Mathematics for AI
  Days  35- 44  Data work: EDA, cleaning, feature engineering
  Days  45- 74  Classical machine learning
  Days  75-104  Deep learning foundations
  Days 105-119  Computer vision
  Days 120-149  NLP, transformers and LLMs
  Days 150-174  LLM engineering: prompting, RAG, agents, tuning, evals
  Days 175-190  Production AI: serving, MLOps, scale, safety
  Days 191-200  Capstones and career
"""
from __future__ import annotations

CURRICULUM: list[tuple[int, str, list[str]]] = []


def add(start: int, themes: list[tuple[str, list[str]]]) -> None:
    day = start
    for theme, concepts in themes:
        assert len(concepts) == 10, f"Day {day} ({theme}): need 10 concepts, got {len(concepts)}"
        CURRICULUM.append((day, theme, concepts))
        day += 1


# ---------------- Phase 1: Python & the data toolkit (1-15) ----------------
add(1, [
    ("Setting up your AI workbench", [
        "Why Python owns AI",
        "Installing Python and checking the version",
        "Virtual environments with venv",
        "pip install and requirements.txt",
        "Choosing an editor: VS Code basics",
        "Jupyter notebooks vs .py scripts",
        "Google Colab and free GPUs",
        "Reading a traceback without panic",
        "Your first script: hello, model",
        "How to use this 200-day course",
    ]),
    ("Python essentials refresher", [
        "Variables, types and dynamic typing",
        "Numbers, strings and f-strings",
        "Lists, tuples, sets, dicts",
        "Slicing and indexing rules",
        "if/elif/else and truthiness",
        "for and while loops",
        "Functions, arguments and defaults",
        "Scope and the mutable default trap",
        "Modules, imports and __main__",
        "Reading the standard library docs",
    ]),
    ("Pythonic data handling", [
        "List comprehensions",
        "Dict and set comprehensions",
        "Generators and yield",
        "enumerate, zip and unpacking",
        "map, filter and lambda",
        "sorted with key functions",
        "collections: Counter, defaultdict",
        "itertools for combinatorics",
        "Lazy evaluation for big data",
        "Choosing the right container",
    ]),
    ("Files, JSON and the filesystem", [
        "Reading and writing text files",
        "Context managers and with",
        "CSV files with the csv module",
        "JSON serialisation and parsing",
        "pathlib for portable paths",
        "Encoding: UTF-8 and why it bites",
        "Working with large files line by line",
        "Compressed files: gzip and zip",
        "Environment variables and secrets",
        "A tiny dataset downloader script",
    ]),
    ("Objects, errors and clean code", [
        "Classes and instances",
        "__init__, attributes and methods",
        "Dunder methods: __repr__, __len__",
        "Dataclasses for config objects",
        "Inheritance vs composition",
        "Exceptions: raise, try, except",
        "Custom exception classes",
        "assert for invariants",
        "Type hints and why they help",
        "Writing code your future self can read",
    ]),
    ("NumPy foundations", [
        "Why NumPy is fast: contiguous memory",
        "Creating arrays: array, zeros, arange, linspace",
        "dtype and memory footprint",
        "Shape, reshape and ravel",
        "Indexing, slicing and views vs copies",
        "Boolean masking",
        "Fancy indexing",
        "Vectorisation vs Python loops",
        "Random numbers with default_rng",
        "Timing a vectorised speedup",
    ]),
    ("NumPy for maths", [
        "Element-wise arithmetic",
        "Broadcasting rules",
        "Reductions: sum, mean, max along an axis",
        "Matrix multiplication with @",
        "Transpose and axis swapping",
        "Stacking: concatenate, vstack, hstack",
        "np.where and conditional logic",
        "Sorting and argsort",
        "Saving and loading .npy files",
        "Common shape errors and how to read them",
    ]),
    ("pandas: Series and DataFrame", [
        "Series vs DataFrame vs ndarray",
        "Reading CSV, Excel and JSON",
        "head, info, describe, dtypes",
        "Selecting columns and rows",
        "loc vs iloc",
        "Boolean filtering",
        "Adding and dropping columns",
        "The index and reset_index",
        "SettingWithCopyWarning explained",
        "Writing results back to disk",
    ]),
    ("pandas: reshape and aggregate", [
        "groupby: split, apply, combine",
        "Aggregations: sum, mean, count, nunique",
        "agg with multiple functions",
        "merge and join semantics",
        "concat for stacking frames",
        "pivot_table and crosstab",
        "melt: wide to long",
        "apply, map and when to avoid them",
        "Sorting and ranking",
        "Chaining without losing readability",
    ]),
    ("Working with time and text in pandas", [
        "Parsing dates with to_datetime",
        "DatetimeIndex and resample",
        "Rolling windows and expanding",
        "Time zones and the UTC rule",
        "String methods with .str",
        "Regex extraction in pandas",
        "Categorical dtype for memory",
        "Duplicates: find and drop",
        "Memory profiling a DataFrame",
        "A monthly report in 20 lines",
    ]),
    ("Visualisation with matplotlib", [
        "Figure and Axes: the object API",
        "Line, scatter and bar plots",
        "Histograms and density",
        "Subplots and shared axes",
        "Labels, titles, legends, annotation",
        "Colour choices that survive printing",
        "Log scales and when to use them",
        "Saving figures for reports",
        "Plotting a model's residuals",
        "Plot first, model second",
    ]),
    ("Statistical plotting and EDA visuals", [
        "seaborn on top of matplotlib",
        "Distribution plots: hist, kde, box, violin",
        "Pairplots and correlation heatmaps",
        "Categorical comparisons",
        "Scatter with hue and size encoding",
        "Faceting by a grouping variable",
        "Spotting skew and outliers visually",
        "Detecting non-linearity",
        "Chart types that mislead",
        "Building a one-page EDA report",
    ]),
    ("SQL for AI practitioners", [
        "Why SQL is still where the data lives",
        "SELECT, WHERE, ORDER BY, LIMIT",
        "GROUP BY and HAVING",
        "JOIN types and row explosions",
        "Window functions for lag features",
        "CTEs for readable queries",
        "sqlite3 from Python",
        "pandas read_sql and to_sql",
        "Pushing aggregation to the database",
        "Query performance basics",
    ]),
    ("Git, environments and reproducibility", [
        "Why every experiment needs a commit",
        "git init, add, commit, log",
        "Branching and merging",
        "Writing a useful .gitignore for ML",
        "Never commit data or secrets",
        "Pinning versions in requirements.txt",
        "Seeding every random source",
        "Recording the data version",
        "A reproducible experiment checklist",
        "Publishing a project to GitHub",
    ]),
    ("PROJECT: dataset explorer CLI", [
        "Framing the tool: what question does it answer",
        "Loading any CSV robustly",
        "Auto-detecting column types",
        "Null and cardinality report",
        "Summary statistics per column type",
        "Correlation with the target column",
        "Generating plots to a folder",
        "Command-line arguments with argparse",
        "Writing a markdown report file",
        "Packaging and reusing the tool",
    ]),
])

# ---------------- Phase 2: Mathematics for AI (16-34) ----------------
add(16, [
    ("Vectors and vector spaces", [
        "What a vector represents in ML",
        "Vector addition and scaling",
        "The dot product and its meaning",
        "Norms: L1, L2, infinity",
        "Unit vectors and normalisation",
        "Cosine similarity",
        "Orthogonality and projection",
        "Linear independence and basis",
        "Vectors as features, vectors as embeddings",
        "Implementing vector ops in NumPy",
    ]),
    ("Matrices and linear transformations", [
        "A matrix as a transformation",
        "Matrix multiplication rules and shapes",
        "Identity and inverse matrices",
        "Transpose and symmetric matrices",
        "Determinant and what zero means",
        "Rank and rank deficiency",
        "Solving linear systems with solve",
        "Why inv() is the wrong tool",
        "Sparse matrices and when they matter",
        "Batched matrix operations",
    ]),
    ("Eigenvalues, SVD and decomposition", [
        "Eigenvectors as invariant directions",
        "Eigenvalues as stretch factors",
        "The characteristic equation",
        "Diagonalisation",
        "Singular value decomposition",
        "Low-rank approximation",
        "SVD for image compression",
        "Condition number and numerical stability",
        "Connection to PCA",
        "Connection to LoRA adapters",
    ]),
    ("Calculus: derivatives and gradients", [
        "The derivative as a rate of change",
        "Rules: power, product, quotient, chain",
        "Partial derivatives",
        "The gradient vector",
        "Directional derivatives",
        "Numeric differentiation and gradient checking",
        "The Jacobian",
        "The Hessian and curvature",
        "Why gradients drive all of deep learning",
        "Hand-deriving a two-layer gradient",
    ]),
    ("Optimisation theory", [
        "Objective functions and minima",
        "Convex vs non-convex landscapes",
        "Local minima, saddle points, plateaus",
        "Gradient descent in one dimension",
        "The learning rate trade-off",
        "Momentum intuition",
        "Newton's method and why we rarely use it",
        "Constrained optimisation and Lagrange multipliers",
        "Stopping criteria",
        "Implementing descent from scratch",
    ]),
    ("Probability foundations", [
        "Sample spaces and events",
        "Axioms of probability",
        "Independence and conditional probability",
        "Bayes' rule",
        "Prior, likelihood, posterior",
        "The base rate fallacy",
        "Random variables",
        "Expectation and variance",
        "Law of large numbers",
        "Monte Carlo estimation",
    ]),
    ("Probability distributions", [
        "Discrete vs continuous distributions",
        "Bernoulli and binomial",
        "Poisson for counts",
        "Uniform distribution",
        "The Gaussian and the CLT",
        "Exponential and heavy tails",
        "Multivariate Gaussian and covariance",
        "Sampling from a distribution",
        "Choosing a likelihood for your data",
        "How the likelihood picks your loss function",
    ]),
    ("Descriptive statistics", [
        "Mean, median and mode",
        "Variance and standard deviation",
        "Quantiles, percentiles and IQR",
        "Skewness and kurtosis",
        "Covariance and correlation",
        "Correlation is not causation",
        "Robust statistics and outliers",
        "Standardisation and z-scores",
        "Simpson's paradox",
        "Summarising a dataset honestly",
    ]),
    ("Inferential statistics", [
        "Population vs sample",
        "Sampling distributions and standard error",
        "Confidence intervals",
        "Null and alternative hypotheses",
        "p-values and what they are not",
        "t-test and chi-square test",
        "Type I and Type II errors",
        "Statistical power and sample size",
        "Multiple comparisons and correction",
        "Bootstrapping without formulas",
    ]),
    ("A/B testing and experiment design", [
        "Framing a decision as an experiment",
        "Randomisation and control groups",
        "Choosing a primary metric",
        "Minimum detectable effect",
        "Deciding sample size up front",
        "Peeking and why it inflates false positives",
        "Guardrail metrics",
        "Novelty and seasonality effects",
        "Analysing an A/B result",
        "When an A/B test is the wrong tool",
    ]),
    ("Information theory", [
        "Information as surprise",
        "Entropy",
        "Cross-entropy",
        "KL divergence",
        "Mutual information",
        "Perplexity in language models",
        "Coding length intuition",
        "Entropy in decision-tree splits",
        "Cross-entropy as the classification loss",
        "Computing all of these in NumPy",
    ]),
    ("Linear algebra in practice", [
        "Representing a dataset as a matrix",
        "Feature scaling as a linear map",
        "Normal equations for least squares",
        "Numerical stability in practice",
        "float32 vs float64 trade-offs",
        "Broadcasting pitfalls in real code",
        "Einstein summation with einsum",
        "Memory layout and cache effects",
        "Benchmarking matrix operations",
        "Reading shapes in a model summary",
    ]),
    ("Discrete maths for AI", [
        "Sets, relations and functions",
        "Combinatorics: permutations and combinations",
        "Graphs, nodes and edges",
        "Adjacency matrices",
        "Trees and traversal",
        "Big-O notation",
        "Complexity of common ML operations",
        "Recursion and dynamic programming",
        "Hashing and hash collisions",
        "Why complexity decides your architecture",
    ]),
    ("Numerical computing pitfalls", [
        "Floating point representation",
        "Catastrophic cancellation",
        "Overflow and underflow",
        "The log-sum-exp trick",
        "Epsilon in denominators",
        "NaN propagation and how to find the source",
        "Deterministic seeds vs true randomness",
        "Reproducibility across hardware",
        "Numerical gradient checking",
        "Debugging a silently wrong computation",
    ]),
    ("Bayesian thinking", [
        "Frequentist vs Bayesian views",
        "Choosing a prior",
        "Conjugate priors: Beta-Binomial",
        "Updating beliefs with evidence",
        "Credible intervals vs confidence intervals",
        "Bayesian A/B testing",
        "Naive Bayes as a Bayesian classifier",
        "MAP vs MLE estimation",
        "Uncertainty that a point estimate hides",
        "A Beta-Binomial update in code",
    ]),
    ("Linear models, mathematically", [
        "The linear model equation",
        "Least squares as a projection",
        "Deriving the normal equations",
        "Gradient descent solution",
        "Adding a bias term correctly",
        "Polynomial features",
        "Multicollinearity and its symptoms",
        "Ridge as constrained least squares",
        "Lasso and sparsity geometry",
        "Interpreting coefficients honestly",
    ]),
    ("Logistic regression, mathematically", [
        "From linear score to probability",
        "The sigmoid and the logit",
        "Odds and log-odds interpretation",
        "Maximum likelihood for Bernoulli data",
        "Deriving the cross-entropy loss",
        "The gradient of logistic loss",
        "Decision boundaries",
        "Multiclass with softmax",
        "Regularised logistic regression",
        "Implementing it from scratch",
    ]),
    ("Distance, similarity and geometry", [
        "Euclidean and Manhattan distance",
        "Minkowski family",
        "Cosine distance vs Euclidean",
        "Mahalanobis distance",
        "Jaccard and set similarity",
        "Edit distance for strings",
        "The curse of dimensionality",
        "Metric vs non-metric similarity",
        "Choosing a distance for your data",
        "Distances that power vector search",
    ]),
    ("PROJECT: maths engine from scratch", [
        "Goal: a tiny numeric library you understand fully",
        "Vector and matrix helpers",
        "Numeric gradient utility",
        "Gradient descent optimiser",
        "Linear regression via normal equations",
        "Linear regression via gradient descent",
        "Logistic regression from scratch",
        "Validating against scikit-learn",
        "Writing assertions as your test suite",
        "What you now never have to take on faith",
    ]),
])

# ---------------- Phase 3: Data work (35-44) ----------------
add(35, [
    ("The machine learning problem framing", [
        "Starting from the decision, not the data",
        "Supervised, unsupervised, reinforcement",
        "Classification vs regression vs ranking",
        "Choosing a target variable",
        "Choosing an evaluation metric",
        "Defining the unit of prediction",
        "Baselines you must beat",
        "Feasibility: is the signal even there",
        "When not to use machine learning",
        "Writing a one-page problem statement",
    ]),
    ("Getting data", [
        "Public dataset sources",
        "APIs and pagination",
        "Web scraping ethics and robots.txt",
        "Database extracts",
        "File formats: CSV, Parquet, JSONL",
        "Parquet and columnar storage",
        "Data licensing and terms of use",
        "Personally identifiable information",
        "Sampling a large source safely",
        "Documenting data provenance",
    ]),
    ("Exploratory data analysis", [
        "First five questions of any dataset",
        "Shape, dtypes, memory",
        "Univariate distributions",
        "Bivariate relationships with the target",
        "Correlation matrices and their limits",
        "Segment analysis by group",
        "Time trends in the data",
        "Finding data-entry errors",
        "Documenting surprises as you go",
        "Turning EDA into modelling hypotheses",
    ]),
    ("Data cleaning", [
        "Missing values: why before how",
        "Deletion strategies",
        "Simple imputation: mean, median, mode",
        "Model-based imputation",
        "Missingness indicator columns",
        "Outlier detection methods",
        "Winsorising vs removing",
        "Fixing inconsistent categories",
        "Deduplication strategies",
        "A reusable cleaning function",
    ]),
    ("Feature engineering fundamentals", [
        "Features carry more weight than algorithms",
        "Ratios and differences",
        "Aggregations over groups",
        "Date and time features",
        "Lag and rolling features",
        "Binning and discretisation",
        "Interaction terms",
        "Domain features from expert knowledge",
        "Text length and simple text features",
        "Documenting every feature's meaning",
    ]),
    ("Encoding and scaling", [
        "One-hot encoding",
        "Ordinal encoding when order is real",
        "Target encoding and its leakage risk",
        "Hashing trick for high cardinality",
        "Handling unseen categories at inference",
        "StandardScaler vs MinMaxScaler",
        "RobustScaler for outlier-heavy data",
        "Log and power transforms",
        "Which models need scaling and which do not",
        "Fitting transforms on train only",
    ]),
    ("Data splitting done right", [
        "Train, validation and test roles",
        "Random split",
        "Stratified split for imbalance",
        "Group split to avoid entity leakage",
        "Time-based split for temporal data",
        "K-fold cross-validation",
        "Stratified and grouped K-fold",
        "Nested cross-validation",
        "How many splits is too many",
        "Locking the test set away",
    ]),
    ("Data leakage hunting", [
        "What leakage actually is",
        "Preprocessing leakage",
        "Target leakage from future columns",
        "Duplicate rows across splits",
        "Group leakage: same entity both sides",
        "Temporal leakage",
        "Leakage through feature selection",
        "Symptoms: impossible scores",
        "A leakage audit checklist",
        "Fixing a leak without starting over",
    ]),
    ("Data validation and contracts", [
        "Schema as a contract",
        "Range and type assertions",
        "Null rate thresholds",
        "Category allowlists",
        "Distribution checks against a baseline",
        "Row count sanity checks",
        "Failing loudly vs failing quietly",
        "Validation in the training pipeline",
        "Validation at inference time",
        "Writing a validate() function with asserts",
    ]),
    ("PROJECT: end-to-end data pipeline", [
        "Goal: raw file to model-ready matrix",
        "Ingest with schema validation",
        "Cleaning stage with logged decisions",
        "Feature engineering stage",
        "Encoding and scaling inside a Pipeline",
        "Train/validation/test split strategy",
        "Persisting the fitted pipeline",
        "Unit tests for each stage",
        "Running the whole thing from one command",
        "A data card describing the result",
    ]),
])

# ---------------- Phase 4: Classical machine learning (45-74) ----------------
add(45, [
    ("Your first model, end to end", [
        "The scikit-learn estimator API",
        "fit, predict, score",
        "Loading a built-in dataset",
        "Splitting the data",
        "Training a logistic regression",
        "Reading the accuracy honestly",
        "Comparing against a dummy baseline",
        "Inspecting the coefficients",
        "Saving and reloading the model",
        "The seven-line template you will reuse forever",
    ]),
    ("Linear regression in practice", [
        "When a straight line is the right model",
        "Fitting with scikit-learn",
        "Interpreting coefficients and units",
        "Residual plots and what they reveal",
        "Heteroscedasticity",
        "Polynomial regression",
        "Multicollinearity in real data",
        "Robust regression for outliers",
        "Predicting with confidence intervals",
        "House-price regression walkthrough",
    ]),
    ("Regularised linear models", [
        "Why unregularised models overfit wide data",
        "Ridge regression",
        "Lasso and automatic feature selection",
        "Elastic net",
        "Choosing alpha with cross-validation",
        "The scaling requirement",
        "Coefficient paths",
        "Regularisation for logistic regression",
        "Sparse models for interpretability",
        "Comparing all four on one dataset",
    ]),
    ("Classification metrics", [
        "The confusion matrix",
        "Accuracy and its blind spot",
        "Precision and recall",
        "The F1 score and F-beta",
        "Specificity and false positive rate",
        "The ROC curve and AUC",
        "Precision-recall curves for imbalance",
        "Threshold tuning as a business decision",
        "Multiclass averaging: macro, micro, weighted",
        "Choosing the metric before the model",
    ]),
    ("Regression metrics and residuals", [
        "MAE and its interpretation",
        "MSE and RMSE",
        "R-squared and adjusted R-squared",
        "MAPE and its zero problem",
        "Choosing a metric from the cost of error",
        "Baseline: predicting the mean",
        "Residual analysis",
        "Error distribution by segment",
        "Prediction intervals",
        "Reporting results without overclaiming",
    ]),
    ("k-nearest neighbours", [
        "The idea: similarity is prediction",
        "Choosing k",
        "Distance metrics and weighting",
        "Why scaling is mandatory",
        "kNN for regression",
        "Computational cost at prediction time",
        "KD-trees and ball trees",
        "The curse of dimensionality",
        "kNN as the ancestor of vector search",
        "Implementing kNN from scratch",
    ]),
    ("Naive Bayes", [
        "The conditional independence assumption",
        "Gaussian Naive Bayes",
        "Multinomial Naive Bayes for text",
        "Bernoulli Naive Bayes",
        "Laplace smoothing",
        "Why it works despite a false assumption",
        "Speed as a feature",
        "Calibration problems",
        "A spam classifier in 10 lines",
        "When to prefer it over logistic regression",
    ]),
    ("Decision trees", [
        "Splitting to increase purity",
        "Gini impurity vs entropy",
        "Information gain",
        "Recursive partitioning",
        "Depth, leaf size and pruning",
        "Handling categorical and missing values",
        "Regression trees",
        "Reading a tree as rules",
        "Instability of single trees",
        "Visualising and exporting a tree",
    ]),
    ("Ensembles: bagging and random forests", [
        "Wisdom of uncorrelated errors",
        "Bootstrap sampling",
        "Bagging",
        "Random feature subsets",
        "Out-of-bag error estimation",
        "Tuning a random forest",
        "Feature importance and its bias",
        "Permutation importance",
        "Extremely randomised trees",
        "Random forest as the tabular default",
    ]),
    ("Boosting", [
        "Sequential error correction",
        "AdaBoost intuition",
        "Gradient boosting as gradient descent in function space",
        "Learning rate and number of trees",
        "Tree depth in boosting",
        "Early stopping with a validation set",
        "XGBoost, LightGBM, CatBoost compared",
        "HistGradientBoosting in scikit-learn",
        "Handling categorical features natively",
        "Why boosting still beats deep nets on tables",
    ]),
    ("Support vector machines", [
        "Maximum margin classification",
        "Support vectors",
        "The C parameter and soft margins",
        "Hinge loss",
        "The kernel trick",
        "RBF, polynomial and linear kernels",
        "Gamma and the bias-variance effect",
        "SVM for regression (SVR)",
        "Scaling requirements and cost at scale",
        "When SVMs still win",
    ]),
    ("Model selection and validation strategy", [
        "Comparing models fairly",
        "Cross-validation as the default",
        "Repeated and stratified CV",
        "Standard error across folds",
        "Statistical comparison of two models",
        "The one-standard-error rule",
        "Nested CV for honest estimates",
        "Validation curves",
        "Learning curves and what they diagnose",
        "Choosing simplest-that-works",
    ]),
    ("Hyperparameter optimisation", [
        "Parameters vs hyperparameters",
        "Manual tuning and its limits",
        "Grid search",
        "Random search and why it wins",
        "Bayesian optimisation",
        "Optuna and pruning bad trials",
        "Successive halving",
        "Search spaces that make sense",
        "Budgeting compute for search",
        "Logging every trial",
    ]),
    ("Handling imbalanced data", [
        "Why accuracy lies here",
        "Class weights",
        "Threshold moving",
        "Random over- and under-sampling",
        "SMOTE and synthetic minority points",
        "Where resampling must happen in the pipeline",
        "Anomaly detection framing instead",
        "Cost-sensitive learning",
        "Choosing PR-AUC over ROC-AUC",
        "A fraud detection walkthrough",
    ]),
    ("Unsupervised learning: clustering", [
        "What clustering can and cannot tell you",
        "K-means and Lloyd's algorithm",
        "Choosing k: elbow and silhouette",
        "K-means++ initialisation",
        "Limitations: shape and scale assumptions",
        "DBSCAN and density clustering",
        "Hierarchical clustering and dendrograms",
        "Gaussian mixture models",
        "Evaluating clusters without labels",
        "Customer segmentation walkthrough",
    ]),
    ("Dimensionality reduction", [
        "Why high dimensions hurt",
        "PCA step by step",
        "Explained variance and choosing components",
        "PCA for visualisation vs for modelling",
        "Kernel PCA",
        "t-SNE and its pitfalls",
        "UMAP",
        "Truncated SVD for sparse text",
        "Feature selection vs feature extraction",
        "Compressing a dataset without losing signal",
    ]),
    ("Anomaly detection", [
        "Framing: rare, unlabelled, costly",
        "Statistical thresholds and z-scores",
        "Isolation Forest",
        "One-class SVM",
        "Local Outlier Factor",
        "Reconstruction error methods",
        "Time-series anomaly detection",
        "Evaluating with few or no labels",
        "Alert fatigue and precision",
        "A server-metrics anomaly detector",
    ]),
    ("Feature importance and model explanation", [
        "Global vs local explanation",
        "Coefficients in linear models",
        "Impurity importance and its bias",
        "Permutation importance",
        "Partial dependence plots",
        "Individual conditional expectation",
        "SHAP values",
        "LIME",
        "Explaining to a non-technical stakeholder",
        "Explanation is not causation",
    ]),
    ("Calibration and probability quality", [
        "What a calibrated probability means",
        "Reliability diagrams",
        "Brier score",
        "Platt scaling",
        "Isotonic regression",
        "Why boosted trees are miscalibrated",
        "Calibration under class imbalance",
        "Calibrating on a held-out set",
        "Decision thresholds from calibrated scores",
        "Expected value of a decision",
    ]),
    ("Ensembling your own models", [
        "Why ensembles work",
        "Voting classifiers: hard and soft",
        "Averaging regressors",
        "Weighted blending",
        "Stacking with a meta-learner",
        "Out-of-fold predictions for stacking",
        "Diversity beats individual strength",
        "Complexity cost in production",
        "When a single model is the right call",
        "Building a stacked ensemble correctly",
    ]),
    ("Recommender systems", [
        "Content-based filtering",
        "Collaborative filtering",
        "User-item matrices and sparsity",
        "Matrix factorisation",
        "Implicit vs explicit feedback",
        "The cold-start problem",
        "Popularity bias and feedback loops",
        "Ranking metrics: precision@k, NDCG",
        "Candidate generation and reranking",
        "A movie recommender walkthrough",
    ]),
    ("Time series analysis", [
        "What makes time series different",
        "Trend, seasonality, residual decomposition",
        "Stationarity and differencing",
        "Autocorrelation and partial autocorrelation",
        "ARIMA family",
        "Exponential smoothing",
        "Prophet-style additive models",
        "Lag and rolling features for ML models",
        "Time-based cross-validation",
        "Forecast evaluation and backtesting",
    ]),
    ("Survival and duration models", [
        "Time-to-event framing",
        "Censoring",
        "Kaplan-Meier curves",
        "Hazard functions",
        "Cox proportional hazards",
        "Churn as a survival problem",
        "Features that change over time",
        "Evaluating survival models",
        "Business use: retention and maintenance",
        "When plain classification is enough",
    ]),
    ("Causal inference basics", [
        "Prediction vs intervention",
        "Confounders",
        "Randomised experiments as the gold standard",
        "Propensity score matching",
        "Difference-in-differences",
        "Instrumental variables",
        "Directed acyclic graphs",
        "Uplift modelling",
        "Why ML models answer the wrong question",
        "Asking causal questions honestly",
    ]),
    ("Working with text, classically", [
        "Text preprocessing pipeline",
        "Tokenisation basics",
        "Stopwords, stemming, lemmatisation",
        "Bag of words",
        "TF-IDF",
        "N-grams",
        "Character n-grams for noisy text",
        "Text classification with linear models",
        "Topic modelling with LDA",
        "The baseline every LLM must beat",
    ]),
    ("Working with images, classically", [
        "Images as arrays",
        "Colour spaces and channels",
        "Resizing, cropping, normalising",
        "Histogram features",
        "Edge detection and filters",
        "HOG and SIFT descriptors",
        "Classical image classification",
        "Data augmentation before deep learning",
        "When classical CV still wins",
        "Loading an image dataset efficiently",
    ]),
    ("Scaling classical ML", [
        "When your data stops fitting in memory",
        "Chunked reading with pandas",
        "Sparse matrices for text",
        "Partial fit and online learning",
        "Feature hashing",
        "Sampling strategies that preserve signal",
        "Dask and out-of-core dataframes",
        "Parallelism with n_jobs",
        "Profiling before optimising",
        "Knowing when to move to a database",
    ]),
    ("Debugging a model that will not learn", [
        "Check the data before the model",
        "Verify labels and their alignment",
        "Overfit a tiny subset deliberately",
        "Check for constant or leaky features",
        "Inspect the loss curve",
        "Compare against the dummy baseline",
        "Look at the worst predictions by hand",
        "Check the split for contamination",
        "Simplify until it works, then rebuild",
        "A systematic debugging checklist",
    ]),
    ("Error analysis", [
        "Why aggregate metrics hide the problem",
        "Slicing errors by segment",
        "Building an error taxonomy",
        "Hand-labelling 50 wrong predictions",
        "Identifying the biggest error bucket",
        "Deciding: more data, better features, or new model",
        "Confusion matrix deep dive",
        "Finding annotation errors in the labels",
        "Prioritising fixes by business impact",
        "Turning error analysis into a backlog",
    ]),
    ("PROJECT: tabular ML competition", [
        "Goal: beat a strong baseline honestly",
        "Framing and metric selection",
        "EDA and leakage audit",
        "Baseline: dummy then logistic regression",
        "Feature engineering iterations",
        "Gradient boosting with early stopping",
        "Cross-validated model comparison",
        "Error analysis and targeted fixes",
        "Final model, calibrated and saved",
        "Writing the results as a report",
    ]),
])

# ---------------- Phase 5: Deep learning foundations (75-104) ----------------
add(75, [
    ("Why deep learning", [
        "Representation learning vs feature engineering",
        "What deep nets buy you and what they cost",
        "Where deep learning beats trees, and where it does not",
        "The hardware and data that made it work",
        "Universal approximation, honestly read",
        "Depth vs width",
        "Modern deep learning timeline",
        "Frameworks: PyTorch, TensorFlow, JAX",
        "The five-line training loop preview",
        "Setting expectations for this phase",
    ]),
    ("The artificial neuron", [
        "Inputs, weights, bias",
        "The weighted sum",
        "Activation functions",
        "The perceptron and its limits",
        "XOR and why one layer is not enough",
        "Layers and forward propagation",
        "Matrix form of a layer",
        "Batch dimension",
        "Counting parameters",
        "A forward pass in pure NumPy",
    ]),
    ("Activation functions", [
        "Why non-linearity is mandatory",
        "Sigmoid and saturation",
        "Tanh",
        "ReLU and dying neurons",
        "Leaky ReLU and PReLU",
        "GELU and SiLU/Swish",
        "Softmax for output distributions",
        "Numerical stability of softmax",
        "Choosing activations per layer",
        "Plotting them all and their gradients",
    ]),
    ("Loss functions", [
        "Loss as the objective you actually optimise",
        "Mean squared error",
        "Mean absolute error and Huber",
        "Binary cross-entropy",
        "Categorical cross-entropy",
        "Logits vs probabilities in loss functions",
        "Class weights inside the loss",
        "Label smoothing",
        "Contrastive and triplet loss",
        "Custom losses for business costs",
    ]),
    ("Backpropagation from scratch", [
        "The computational graph",
        "Forward pass caching",
        "The chain rule, backwards",
        "Gradients of common operations",
        "Backprop through a two-layer network",
        "Vectorised gradient computation",
        "Gradient checking",
        "Common sign and shape errors",
        "Why frameworks exist",
        "Implementing a full training loop in NumPy",
    ]),
    ("Optimisers", [
        "Batch, stochastic and mini-batch descent",
        "Learning rate: the master knob",
        "Momentum",
        "Nesterov accelerated gradient",
        "AdaGrad and RMSProp",
        "Adam",
        "AdamW and decoupled weight decay",
        "Choosing an optimiser in practice",
        "Optimiser state and memory cost",
        "Implementing Adam from scratch",
    ]),
    ("Learning rate schedules", [
        "Why a constant learning rate is rarely best",
        "Step decay",
        "Exponential decay",
        "Cosine annealing",
        "Warmup and why transformers need it",
        "One-cycle policy",
        "Reduce on plateau",
        "Learning rate range test",
        "Interaction with batch size",
        "Reading a loss curve to pick a schedule",
    ]),
    ("Initialisation and normalisation", [
        "Why zero initialisation fails",
        "Random initialisation scale",
        "Xavier/Glorot initialisation",
        "He initialisation for ReLU",
        "Batch normalisation",
        "Train vs eval mode",
        "Layer normalisation",
        "Group and RMS normalisation",
        "Where to place normalisation layers",
        "Diagnosing activation blow-up",
    ]),
    ("Regularisation in deep nets", [
        "Overfitting in high-capacity models",
        "Weight decay",
        "Dropout",
        "Inverted dropout at inference",
        "Early stopping",
        "Data augmentation as regularisation",
        "Label smoothing",
        "Mixup and CutMix",
        "Ensembling and snapshot ensembles",
        "Choosing regularisation by symptom",
    ]),
    ("PyTorch fundamentals", [
        "Tensors and dtypes",
        "Tensor operations mirror NumPy",
        "CPU and GPU devices",
        "requires_grad and autograd",
        "backward() and .grad",
        "Detaching from the graph",
        "nn.Module and parameters",
        "nn.Sequential",
        "The canonical training loop",
        "Common PyTorch error messages",
    ]),
    ("PyTorch data pipeline", [
        "Dataset and __getitem__",
        "DataLoader, batching and shuffling",
        "num_workers and prefetching",
        "Custom collate functions",
        "Transforms and augmentation",
        "Handling variable-length inputs",
        "Weighted samplers for imbalance",
        "Reproducible shuffling with seeds",
        "Profiling a slow data loader",
        "Building a Dataset for your own files",
    ]),
    ("Training loop engineering", [
        "Train and validation phases",
        "model.train() vs model.eval()",
        "torch.no_grad() for inference",
        "Tracking metrics per epoch",
        "Checkpointing and resuming",
        "Saving the best model by validation score",
        "Gradient clipping",
        "Gradient accumulation",
        "Mixed precision training",
        "A reusable Trainer you actually own",
    ]),
    ("Debugging neural networks", [
        "Overfit a single batch first",
        "Check loss at initialisation",
        "Verify the data reaching the model",
        "Shape errors and how to read them",
        "NaN loss: causes and fixes",
        "Exploding and vanishing gradients",
        "Learning rate diagnosis from the curve",
        "Dead ReLU detection",
        "Comparing against a simple baseline",
        "A deep learning debugging checklist",
    ]),
    ("Convolutional neural networks", [
        "Why dense layers fail on images",
        "The convolution operation",
        "Kernels, stride and padding",
        "Feature maps and channels",
        "Receptive field",
        "Pooling layers",
        "Parameter sharing and translation equivariance",
        "A classic CNN architecture",
        "Computing output shapes",
        "Implementing a conv by hand",
    ]),
    ("CNN architectures", [
        "LeNet and AlexNet",
        "VGG and stacked small kernels",
        "Inception and multi-scale",
        "ResNet and residual connections",
        "DenseNet",
        "MobileNet and depthwise separable convolutions",
        "EfficientNet and compound scaling",
        "Vision transformers as the alternative",
        "Choosing an architecture for your constraints",
        "Reading an architecture diagram",
    ]),
    ("Training a CNN properly", [
        "Dataset preparation and splits",
        "Normalisation statistics",
        "Augmentation strategy",
        "Choosing batch size",
        "Learning rate finder",
        "Monitoring train vs validation",
        "Confusion matrix on validation",
        "Test-time augmentation",
        "Class imbalance in images",
        "An image classifier walkthrough",
    ]),
    ("Transfer learning", [
        "Why pretrained features transfer",
        "Feature extraction: freeze the backbone",
        "Fine-tuning: unfreeze at a low LR",
        "Replacing the classification head",
        "Discriminative learning rates per layer",
        "How much data you need for each strategy",
        "Domain gap and when transfer fails",
        "Matching preprocessing to the pretrained model",
        "Timm and torchvision model zoos",
        "Fine-tuning on a few hundred images",
    ]),
    ("Sequence models: RNNs", [
        "Sequential data and order",
        "The recurrent cell and hidden state",
        "Backpropagation through time",
        "Vanishing gradients over long sequences",
        "LSTM gates",
        "GRU",
        "Bidirectional RNNs",
        "Sequence-to-sequence architecture",
        "Padding, packing and masks",
        "Why transformers replaced them",
    ]),
    ("Attention mechanisms", [
        "The bottleneck problem in seq2seq",
        "Attention as weighted lookup",
        "Query, key and value",
        "Scaled dot-product attention",
        "The scaling factor and why it matters",
        "Attention masks",
        "Self-attention vs cross-attention",
        "Multi-head attention",
        "Attention weight visualisation",
        "Implementing attention in NumPy",
    ]),
    ("Autoencoders", [
        "Encoder, bottleneck, decoder",
        "Reconstruction loss",
        "Undercomplete vs overcomplete",
        "Denoising autoencoders",
        "Sparse autoencoders",
        "Autoencoders for anomaly detection",
        "Variational autoencoders",
        "The reparameterisation trick",
        "Latent space arithmetic",
        "Building an anomaly detector with one",
    ]),
    ("Generative adversarial networks", [
        "Generator vs discriminator",
        "The minimax objective",
        "Training instability",
        "Mode collapse",
        "DCGAN architecture",
        "Conditional GANs",
        "CycleGAN and unpaired translation",
        "Evaluating generative models",
        "Why diffusion largely replaced GANs",
        "Reading GAN samples, not GAN losses",
    ]),
    ("Diffusion models", [
        "The forward noising process",
        "Learning to denoise",
        "The noise schedule",
        "U-Net as the denoiser",
        "Sampling steps and quality trade-off",
        "Classifier-free guidance",
        "Latent diffusion",
        "Text conditioning",
        "ControlNet and structural conditioning",
        "Compute cost of generation",
    ]),
    ("Embeddings and representation learning", [
        "What an embedding space is",
        "Learned vs engineered features",
        "Word2vec: skip-gram and CBOW",
        "Negative sampling",
        "Sentence and document embeddings",
        "Image embeddings",
        "Contrastive learning",
        "Self-supervised pretext tasks",
        "Evaluating an embedding space",
        "Embeddings as the interface between models",
    ]),
    ("Graph neural networks", [
        "Data that is naturally a graph",
        "Adjacency and node features",
        "Message passing",
        "Graph convolution",
        "GraphSAGE and sampling",
        "Graph attention networks",
        "Node, edge and graph-level tasks",
        "Over-smoothing",
        "Splitting graph data without leakage",
        "Fraud rings as a GNN problem",
    ]),
    ("Reinforcement learning foundations", [
        "Agent, environment, reward",
        "Markov decision processes",
        "Policy and value functions",
        "The Bellman equation",
        "Exploration vs exploitation",
        "Multi-armed bandits",
        "Q-learning",
        "Deep Q-networks",
        "Policy gradients and REINFORCE",
        "Reward hacking",
    ]),
    ("Advanced reinforcement learning", [
        "Actor-critic methods",
        "Advantage estimation",
        "PPO and clipped objectives",
        "Continuous action spaces",
        "Sample efficiency problems",
        "Offline reinforcement learning",
        "Simulation and the sim-to-real gap",
        "RL from human feedback preview",
        "When RL is the wrong tool",
        "A gridworld agent from scratch",
    ]),
    ("Model compression", [
        "Why inference cost matters more than training cost",
        "Quantisation: int8 and int4",
        "Post-training vs quantisation-aware training",
        "Pruning: structured and unstructured",
        "Knowledge distillation",
        "Low-rank factorisation",
        "Operator fusion",
        "ONNX and runtime portability",
        "Measuring the accuracy/latency trade-off",
        "Shrinking a model for edge deployment",
    ]),
    ("Hardware and performance", [
        "CPU vs GPU vs TPU",
        "Memory bandwidth as the real bottleneck",
        "Batch size and utilisation",
        "Mixed precision: fp16 and bf16",
        "Gradient checkpointing",
        "Profiling a training run",
        "Data loading bottlenecks",
        "Multi-GPU data parallelism",
        "Model and pipeline parallelism",
        "Estimating training cost before you start",
    ]),
    ("Neural network design decisions", [
        "Starting from a known-good architecture",
        "Choosing depth and width",
        "Skip connections by default",
        "Normalisation placement",
        "Regularisation budget",
        "Output layer for your task",
        "Loss matching the output layer",
        "Parameter count vs data size",
        "Ablation studies",
        "Documenting why each choice was made",
    ]),
    ("PROJECT: deep learning image classifier", [
        "Goal: a fine-tuned classifier you can defend",
        "Dataset collection and cleaning",
        "Stratified splits and a locked test set",
        "Baseline: logistic regression on embeddings",
        "Transfer learning with a pretrained backbone",
        "Augmentation and regularisation tuning",
        "Training loop with checkpointing",
        "Error analysis on the worst classes",
        "Exporting for inference",
        "A short model card",
    ]),
])

# ---------------- Phase 6: Computer vision (105-119) ----------------
add(105, [
    ("Image fundamentals", [
        "Pixels, channels and bit depth",
        "Colour spaces: RGB, HSV, grayscale",
        "Image file formats and compression",
        "Loading images with PIL and OpenCV",
        "Resizing and interpolation methods",
        "Aspect ratio and letterboxing",
        "Normalisation for pretrained models",
        "Batching images efficiently",
        "EXIF orientation gotchas",
        "Building an image loading utility",
    ]),
    ("Image preprocessing and augmentation", [
        "Why augmentation works",
        "Geometric transforms",
        "Colour jitter and photometric transforms",
        "Random crop and resize strategies",
        "Cutout, mixup and CutMix",
        "Augmentation that changes the label",
        "Albumentations pipelines",
        "Train vs validation transforms",
        "Augmentation for small datasets",
        "Visualising augmented batches",
    ]),
    ("Object detection", [
        "Detection vs classification",
        "Bounding box formats",
        "Intersection over union",
        "Anchor boxes",
        "Two-stage detectors: R-CNN family",
        "One-stage detectors: YOLO and SSD",
        "Non-maximum suppression",
        "mAP as the detection metric",
        "Annotating a detection dataset",
        "Fine-tuning a detector",
    ]),
    ("Image segmentation", [
        "Semantic vs instance vs panoptic",
        "Per-pixel classification",
        "U-Net architecture",
        "Encoder-decoder with skip connections",
        "Dice and IoU losses",
        "Mask R-CNN",
        "Segment Anything and promptable segmentation",
        "Medical imaging considerations",
        "Annotation cost and weak supervision",
        "Evaluating segmentation quality",
    ]),
    ("Face and person understanding", [
        "Face detection vs recognition",
        "Face embeddings and verification",
        "Landmark detection",
        "Pose estimation",
        "Person re-identification",
        "Bias in face datasets",
        "Privacy and consent",
        "Legal restrictions by jurisdiction",
        "When to refuse to build it",
        "Safer alternatives to face recognition",
    ]),
    ("Video understanding", [
        "Video as a sequence of frames",
        "Frame sampling strategies",
        "Optical flow",
        "Action recognition",
        "3D convolutions",
        "Temporal models over frame features",
        "Object tracking",
        "Real-time constraints",
        "Storage and throughput planning",
        "A simple activity classifier",
    ]),
    ("Vision transformers", [
        "Images as patch sequences",
        "Patch embedding",
        "Positional embeddings for images",
        "ViT architecture",
        "Data hunger of ViTs",
        "DeiT and distillation",
        "Swin and hierarchical attention",
        "ViT vs CNN trade-offs",
        "Fine-tuning a ViT",
        "Attention maps as explanation",
    ]),
    ("Self-supervised vision", [
        "Learning without labels",
        "Contrastive learning: SimCLR",
        "MoCo and memory banks",
        "BYOL without negatives",
        "Masked autoencoders",
        "DINO and self-distillation",
        "Evaluating with linear probes",
        "Pretraining on your own unlabelled data",
        "When self-supervision pays off",
        "Compute realities",
    ]),
    ("CLIP and multimodal vision", [
        "Joint image-text embedding space",
        "Contrastive pretraining at scale",
        "Zero-shot classification",
        "Prompt templates for CLIP",
        "Image search by description",
        "Image captioning",
        "Visual question answering",
        "Vision-language models today",
        "Failure modes of zero-shot",
        "Building a semantic image search",
    ]),
    ("OCR and document AI", [
        "Text detection vs text recognition",
        "Tesseract and classical OCR",
        "Deep OCR models",
        "Layout analysis",
        "Table extraction",
        "Handwriting recognition",
        "Document classification",
        "Key-value extraction from forms",
        "Post-processing and validation rules",
        "An invoice extraction pipeline",
    ]),
    ("Image generation in practice", [
        "Text-to-image workflow",
        "Prompting for images",
        "Negative prompts",
        "Image-to-image and inpainting",
        "Guidance scale and steps",
        "Seeds and reproducibility",
        "LoRA for style adaptation",
        "Upscaling",
        "Content provenance and watermarking",
        "Copyright and dataset questions",
    ]),
    ("Edge and mobile vision", [
        "Latency and power constraints",
        "Model choice for edge devices",
        "Quantised inference",
        "ONNX Runtime and TFLite",
        "Camera pipeline integration",
        "Batching vs streaming",
        "Thermal throttling",
        "On-device privacy advantages",
        "Measuring real device performance",
        "Deploying a detector to a Raspberry Pi",
    ]),
    ("3D and depth", [
        "Depth from stereo",
        "Monocular depth estimation",
        "Point clouds",
        "Voxels and meshes",
        "PointNet",
        "NeRF and neural rendering",
        "Gaussian splatting",
        "Applications in robotics and AR",
        "Data collection challenges",
        "Evaluating 3D reconstructions",
    ]),
    ("Vision system design", [
        "Requirements: accuracy, latency, cost",
        "Data collection plan",
        "Annotation strategy and quality control",
        "Choosing the model family",
        "Handling class imbalance in vision",
        "Monitoring in production",
        "Human-in-the-loop review",
        "Failure modes and fallbacks",
        "Cost per inference",
        "Writing the system design document",
    ]),
    ("PROJECT: computer vision application", [
        "Goal: a working vision service",
        "Defining the detection or classification task",
        "Collecting and annotating data",
        "Baseline model and metric",
        "Training with augmentation",
        "Threshold tuning against business cost",
        "Inference API around the model",
        "Latency measurement and optimisation",
        "Monitoring plan",
        "Demo and documentation",
    ]),
])

# ---------------- Phase 7: NLP, transformers and LLMs (120-149) ----------------
add(120, [
    ("Text processing fundamentals", [
        "Unicode, encodings and normalisation",
        "Whitespace and punctuation handling",
        "Case folding trade-offs",
        "Regular expressions for extraction",
        "Sentence splitting",
        "Language detection",
        "Handling code-mixed text",
        "Cleaning scraped HTML",
        "Text quality filtering",
        "A reusable text cleaning function",
    ]),
    ("Tokenisation", [
        "Why models need tokens, not words",
        "Word-level tokenisation and OOV",
        "Character-level trade-offs",
        "Byte-pair encoding",
        "WordPiece and SentencePiece",
        "Vocabulary size decisions",
        "Special tokens: BOS, EOS, PAD, UNK",
        "Token counts and cost estimation",
        "Tokenisation across languages",
        "Implementing BPE merges by hand",
    ]),
    ("Classical NLP baselines", [
        "Bag of words revisited",
        "TF-IDF for classification",
        "N-gram language models",
        "Naive Bayes for text",
        "Linear SVM for text",
        "Named entity recognition, classically",
        "Rule-based systems that still work",
        "Keyword search and BM25",
        "Measuring the baseline properly",
        "Deciding whether you need an LLM at all",
    ]),
    ("Word embeddings", [
        "Distributional semantics",
        "Word2vec skip-gram",
        "CBOW",
        "Negative sampling",
        "GloVe",
        "FastText and subword vectors",
        "Embedding arithmetic and analogies",
        "Bias encoded in embeddings",
        "Static vs contextual embeddings",
        "Training embeddings on your own corpus",
    ]),
    ("Sequence models for NLP", [
        "RNNs for text",
        "LSTM for sequence labelling",
        "Bidirectional context",
        "Sequence-to-sequence translation",
        "Teacher forcing",
        "Beam search decoding",
        "The context bottleneck",
        "Attention added to seq2seq",
        "Why this architecture ended",
        "What still carries over",
    ]),
    ("The transformer architecture", [
        "The 2017 idea: attention is all you need",
        "Input embeddings and positional encoding",
        "Self-attention block",
        "Multi-head attention",
        "Feed-forward network per position",
        "Residual connections and LayerNorm",
        "Encoder stack",
        "Decoder stack and causal masking",
        "Parameter count breakdown",
        "Drawing the block from memory",
    ]),
    ("Attention deep dive", [
        "Query, key, value projections",
        "Scaled dot-product attention",
        "Causal and padding masks",
        "Cross-attention in encoder-decoder",
        "Attention complexity in sequence length",
        "Flash attention and memory-efficient kernels",
        "Sliding window and sparse attention",
        "Grouped-query and multi-query attention",
        "KV cache during generation",
        "Implementing multi-head attention",
    ]),
    ("Positional information", [
        "Why attention is order-blind",
        "Sinusoidal positional encoding",
        "Learned positional embeddings",
        "Relative position encodings",
        "RoPE rotary embeddings",
        "ALiBi",
        "Context length extension methods",
        "Position and long-context failure",
        "Lost in the middle effect",
        "Choosing an encoding scheme",
    ]),
    ("Transformer families", [
        "Encoder-only: BERT",
        "Masked language modelling",
        "Decoder-only: GPT family",
        "Next-token prediction",
        "Encoder-decoder: T5 and BART",
        "Span corruption objectives",
        "Which family for which task",
        "Model size and capability",
        "Open-weight vs API models",
        "Reading a model card",
    ]),
    ("Fine-tuning encoder models", [
        "Hugging Face transformers basics",
        "AutoTokenizer and AutoModel",
        "Adding a classification head",
        "Dataset formatting and collation",
        "Trainer API vs manual loop",
        "Learning rates for fine-tuning",
        "Freezing layers",
        "Evaluating on a held-out set",
        "Overfitting on small text datasets",
        "A ticket classifier walkthrough",
    ]),
    ("Pretraining language models", [
        "The next-token objective at scale",
        "Data collection and filtering",
        "Deduplication and quality scoring",
        "Tokeniser training",
        "Compute budget and scaling laws",
        "Chinchilla-optimal data ratios",
        "Training instabilities",
        "Evaluation during pretraining",
        "Cost realities",
        "Why almost nobody should pretrain",
    ]),
    ("Post-training: SFT and alignment", [
        "Base models do not follow instructions",
        "Supervised fine-tuning data format",
        "Masking the loss to the response only",
        "Data quality over quantity",
        "Reward models",
        "RLHF with PPO",
        "Direct preference optimisation",
        "Constitutional and rule-based methods",
        "Sycophancy and reward hacking",
        "Evaluating alignment",
    ]),
    ("Parameter-efficient fine-tuning", [
        "Why full fine-tuning is expensive",
        "Adapters",
        "LoRA: the low-rank idea",
        "Rank, alpha and target modules",
        "QLoRA and 4-bit base weights",
        "Prefix and prompt tuning",
        "Merging adapters back",
        "Serving multiple adapters",
        "Choosing PEFT hyperparameters",
        "Fine-tuning a small model on one GPU",
    ]),
    ("Inference and decoding", [
        "Autoregressive generation",
        "Greedy decoding",
        "Temperature",
        "Top-k sampling",
        "Top-p nucleus sampling",
        "Repetition penalties",
        "Beam search for constrained tasks",
        "Stop sequences",
        "Streaming tokens to the user",
        "Choosing decoding settings per task",
    ]),
    ("Serving LLMs efficiently", [
        "Prefill vs decode phases",
        "KV cache memory maths",
        "Continuous batching",
        "PagedAttention and vLLM",
        "Quantised inference: GPTQ, AWQ, GGUF",
        "Speculative decoding",
        "Throughput vs latency trade-offs",
        "Cost per million tokens",
        "Local models with llama.cpp and Ollama",
        "Choosing hosted vs self-hosted",
    ]),
    ("Embeddings and semantic search", [
        "Embedding models today",
        "Symmetric vs asymmetric search",
        "Normalisation and cosine similarity",
        "Approximate nearest neighbour algorithms",
        "HNSW indexes",
        "Vector databases compared",
        "Metadata filtering",
        "Hybrid search with BM25",
        "Evaluating retrieval quality",
        "Building a semantic search over your notes",
    ]),
    ("Text generation quality", [
        "Fluency versus factuality",
        "Hallucination causes",
        "Grounding in sources",
        "Citations and verifiability",
        "Self-consistency sampling",
        "Verification passes",
        "Abstaining when uncertain",
        "Measuring hallucination rate",
        "User-facing uncertainty communication",
        "Designing for graceful wrongness",
    ]),
    ("Summarisation and extraction", [
        "Extractive vs abstractive summarisation",
        "Chunking long documents",
        "Map-reduce summarisation",
        "Refine chains",
        "Structured extraction with schemas",
        "Handling documents beyond context",
        "Evaluating summaries",
        "ROUGE and its limits",
        "Human evaluation rubrics",
        "A meeting-notes summariser",
    ]),
    ("Conversational systems", [
        "Turns, roles and system prompts",
        "Conversation state and memory",
        "Context window management",
        "Summarising older turns",
        "Persona and tone control",
        "Handling out-of-scope requests",
        "Escalation to a human",
        "Multi-turn evaluation",
        "Latency perception and streaming",
        "Building a grounded support bot",
    ]),
    ("Multilingual and Indic NLP", [
        "Tokenisation cost across scripts",
        "Multilingual model families",
        "Cross-lingual transfer",
        "Translation quality evaluation",
        "Code-mixed Hinglish text",
        "Transliteration",
        "Low-resource language strategies",
        "Dataset scarcity workarounds",
        "Evaluation in non-English languages",
        "Building for Indian language users",
    ]),
    ("Speech and audio", [
        "Waveforms and sampling rates",
        "Spectrograms and mel scale",
        "Automatic speech recognition",
        "Whisper and its trade-offs",
        "Diarisation: who spoke when",
        "Text-to-speech",
        "Voice cloning and its ethics",
        "Real-time streaming ASR",
        "Noise robustness",
        "A meeting transcription pipeline",
    ]),
    ("Multimodal models", [
        "Text plus image inputs",
        "How images become tokens",
        "Document and chart understanding",
        "Video understanding with LLMs",
        "Audio-native models",
        "Multimodal prompting patterns",
        "Failure modes on fine detail",
        "Cost of image tokens",
        "Choosing OCR vs a vision model",
        "A screenshot-to-data pipeline",
    ]),
    ("Model evaluation for LLMs", [
        "Why standard benchmarks mislead",
        "Building a golden dataset",
        "Task-specific automatic metrics",
        "Exact match and structured checks",
        "LLM-as-judge",
        "Calibrating a judge against humans",
        "Pairwise comparison and Elo",
        "Regression testing prompts",
        "Evaluating latency and cost too",
        "An eval harness you run on every change",
    ]),
    ("Reasoning and thinking models", [
        "Chain-of-thought prompting",
        "Self-consistency",
        "Extended thinking modes",
        "Tree and graph of thought",
        "Tool use as reasoning support",
        "Verification and self-critique",
        "Where reasoning helps and where it wastes tokens",
        "Reasoning token cost",
        "Reading a reasoning trace critically",
        "Choosing a reasoning budget",
    ]),
    ("Knowledge in language models", [
        "Parametric vs retrieved knowledge",
        "Knowledge cutoffs",
        "Model editing",
        "Knowledge graphs alongside LLMs",
        "Entity linking",
        "Fact verification",
        "Temporal reasoning failures",
        "Numerical and counting weaknesses",
        "When to use a database instead",
        "Designing the knowledge boundary",
    ]),
    ("Small models and local AI", [
        "Why small models matter",
        "Distillation from a large teacher",
        "Task-specific small models",
        "Running models on a laptop",
        "GGUF quantisation levels",
        "Ollama and LM Studio",
        "Privacy advantages of local inference",
        "Latency and cost comparison",
        "Quality gap by task type",
        "Routing between small and large models",
    ]),
    ("Prompt engineering foundations", [
        "A prompt is a specification",
        "Role, task, constraints, format",
        "Zero-shot vs few-shot",
        "Example selection matters",
        "Delimiters and structure",
        "Output format specification",
        "Chain-of-thought when useful",
        "Negative instructions and their weakness",
        "Iterating with a test set",
        "Versioning prompts like code",
    ]),
    ("Advanced prompting patterns", [
        "Decomposition into sub-prompts",
        "Prompt chaining",
        "Self-critique and revision loops",
        "Rubric-based grading prompts",
        "Persona and expertise framing",
        "Handling ambiguity explicitly",
        "Refusal and safe-completion design",
        "Prompt caching for cost",
        "Token budgeting",
        "A prompt library with tests",
    ]),
    ("LLM APIs in code", [
        "Anatomy of a chat completion request",
        "System prompts and message roles",
        "max_tokens and stop conditions",
        "Streaming responses",
        "Retries, timeouts and backoff",
        "Rate limits and concurrency",
        "Cost tracking per request",
        "Prompt caching for stable prefixes",
        "Structured outputs and tool schemas",
        "A resilient API client wrapper",
    ]),
    ("PROJECT: fine-tuned domain assistant", [
        "Goal: a small model specialised to one task",
        "Collecting and curating examples",
        "Formatting an SFT dataset",
        "Choosing base model and LoRA settings",
        "Training run and monitoring",
        "Evaluating against the base model",
        "Comparing against a prompted large model",
        "Cost and latency comparison",
        "Deciding whether tuning was worth it",
        "Packaging the adapter",
    ]),
])

# ---------------- Phase 8: LLM engineering (150-174) ----------------
add(150, [
    ("Designing with LLMs", [
        "What LLMs are good and bad at",
        "Choosing between rules, ML and LLMs",
        "Task decomposition",
        "Deterministic scaffolding around a stochastic core",
        "Where to put validation",
        "Failure budgets",
        "Human-in-the-loop design",
        "Cost modelling before building",
        "Latency budgets",
        "Writing an LLM system design doc",
    ]),
    ("Structured output", [
        "Why free text is hard to use",
        "JSON schemas for outputs",
        "Tool/function calling",
        "Validation and repair loops",
        "Pydantic models for responses",
        "Enums to constrain choices",
        "Handling partial and malformed output",
        "Streaming structured output",
        "Confidence fields and their honesty",
        "A robust extraction service",
    ]),
    ("Retrieval augmented generation basics", [
        "Why RAG instead of fine-tuning",
        "The RAG pipeline end to end",
        "Document loading and parsing",
        "Chunking strategies",
        "Chunk size and overlap trade-offs",
        "Embedding the chunks",
        "Storing vectors with metadata",
        "Retrieving top-k for a query",
        "Assembling the prompt",
        "A minimal RAG in 50 lines",
    ]),
    ("RAG: retrieval quality", [
        "Retrieval is the bottleneck, not generation",
        "Measuring recall@k",
        "Query rewriting",
        "Hypothetical document embeddings",
        "Multi-query retrieval",
        "Hybrid dense plus keyword search",
        "Reranking with a cross-encoder",
        "Metadata filters",
        "Handling tables and code chunks",
        "Building a retrieval eval set",
    ]),
    ("RAG: chunking and parsing", [
        "Structure-aware chunking",
        "Heading hierarchy as context",
        "PDF parsing pitfalls",
        "Tables, figures and captions",
        "Code and config files",
        "Contextual chunk headers",
        "Parent-document retrieval",
        "Deduplication in the index",
        "Incremental index updates",
        "Choosing chunk size empirically",
    ]),
    ("RAG: generation and grounding", [
        "Prompt template for grounded answers",
        "Citation requirements",
        "Instructing abstention",
        "Handling conflicting sources",
        "Answer verification against sources",
        "Showing sources in the UI",
        "Context ordering effects",
        "Token budget allocation",
        "Latency of the full pipeline",
        "Measuring groundedness",
    ]),
    ("Vector databases", [
        "What a vector database actually does",
        "Exact vs approximate search",
        "HNSW and IVF indexes",
        "Recall vs latency tuning",
        "Metadata filtering strategies",
        "Sharding and scale",
        "Options: FAISS, Chroma, Qdrant, pgvector",
        "When Postgres is enough",
        "Index rebuild and update costs",
        "Choosing one for your scale",
    ]),
    ("Agents: the loop", [
        "What makes something an agent",
        "The observe-decide-act loop",
        "Tool definitions and schemas",
        "Tool result formatting",
        "Iteration limits",
        "Termination conditions",
        "State between steps",
        "Error handling inside the loop",
        "Logging every step for debugging",
        "Building a two-tool agent from scratch",
    ]),
    ("Agents: tools and capabilities", [
        "Designing a good tool interface",
        "Read-only vs mutating tools",
        "Search and retrieval tools",
        "Code execution sandboxes",
        "File system access controls",
        "API calling tools",
        "Database query tools with allowlists",
        "Human approval gates",
        "Tool descriptions as prompts",
        "Testing tools independently",
    ]),
    ("Agents: planning and reliability", [
        "Explicit planning steps",
        "Replanning after failure",
        "Subagents and delegation",
        "Parallel tool calls",
        "Context management across long runs",
        "Cost control and budgets",
        "Detecting loops and stalls",
        "Checkpointing long tasks",
        "Determinism where it matters",
        "Evaluating agent trajectories",
    ]),
    ("Model Context Protocol and integrations", [
        "Why a protocol for tools",
        "MCP servers and clients",
        "Resources, tools and prompts",
        "Local vs remote servers",
        "Authentication in integrations",
        "Building a small MCP server",
        "Security review of a third-party server",
        "Versioning tool contracts",
        "Debugging protocol issues",
        "Integrations as the real product surface",
    ]),
    ("Memory for AI applications", [
        "Short-term context vs long-term memory",
        "Conversation summarisation",
        "Fact extraction and storage",
        "Vector memory and its failure modes",
        "Structured memory in a database",
        "Recency, relevance and importance scoring",
        "Forgetting and expiry",
        "Privacy and user control over memory",
        "Memory conflicts and contradictions",
        "Designing a memory schema",
    ]),
    ("Prompt injection and LLM security", [
        "The trust boundary in an LLM app",
        "Direct prompt injection",
        "Indirect injection via documents and web pages",
        "Data exfiltration through tool calls",
        "Confused deputy problems",
        "Delimiting untrusted content",
        "Authorisation in code, not prompts",
        "Output sanitisation before rendering",
        "Sandboxing code execution",
        "A threat model for your app",
    ]),
    ("Safety, moderation and refusals", [
        "Categories of harmful content",
        "Input and output moderation",
        "Refusal design that stays useful",
        "Over-refusal as a real failure",
        "Age and jurisdiction constraints",
        "Escalation paths",
        "Red-teaming your own app",
        "Logging and incident response",
        "Documenting known limitations",
        "Balancing safety and usefulness",
    ]),
    ("Evaluation for LLM applications", [
        "Defining success for a fuzzy task",
        "Golden datasets from real traffic",
        "Deterministic checks first",
        "LLM judges with rubrics",
        "Pairwise preference evaluation",
        "Inter-rater agreement",
        "Regression suites in CI",
        "Online metrics: thumbs, escalation rate",
        "Sampling production traffic for review",
        "Closing the loop from eval to fix",
    ]),
    ("Observability for AI systems", [
        "What to log for every call",
        "Prompt and response capture with privacy",
        "Token and cost accounting",
        "Latency percentiles",
        "Tracing multi-step chains",
        "Error taxonomies",
        "Sampling and retention policies",
        "Dashboards that surface regressions",
        "Alerting on quality, not just uptime",
        "Building a minimal trace viewer",
    ]),
    ("Cost engineering", [
        "Token economics",
        "Prompt compression",
        "Prompt caching",
        "Model routing by difficulty",
        "Small model first, escalate on failure",
        "Batch processing for offline jobs",
        "Caching identical requests",
        "Truncating context intelligently",
        "Measuring cost per resolved task",
        "A cost dashboard for your app",
    ]),
    ("Latency engineering", [
        "Perceived vs actual latency",
        "Streaming first tokens",
        "Parallelising independent calls",
        "Speculative prefetching",
        "Reducing prompt size",
        "Choosing faster models for sub-tasks",
        "Caching retrieval results",
        "Timeouts and fallbacks",
        "Measuring p50, p95, p99",
        "Meeting a latency SLA",
    ]),
    ("Data flywheels", [
        "Capturing user feedback",
        "Implicit signals: edits, retries, abandonment",
        "Building a labelling loop",
        "Active learning: label what is uncertain",
        "Turning corrections into eval cases",
        "Retraining and re-prompting cadence",
        "Avoiding feedback loop bias",
        "Privacy constraints on user data",
        "Measuring flywheel velocity",
        "Designing the loop from day one",
    ]),
    ("Working with unstructured documents", [
        "Document ingestion pipeline",
        "Format detection and routing",
        "PDF text vs scanned PDF",
        "OCR fallback",
        "Layout and reading order",
        "Table extraction strategies",
        "Metadata and provenance",
        "Incremental processing",
        "Quality checks on extraction",
        "A document intelligence service",
    ]),
    ("Code-focused AI", [
        "Code as a modality",
        "Code completion models",
        "Repository-level context",
        "Test generation",
        "Code review assistance",
        "Refactoring with LLMs",
        "Execution feedback loops",
        "Security of generated code",
        "Evaluating code correctness",
        "Building a code assistant workflow",
    ]),
    ("Building AI product features", [
        "Choosing a feature worth AI",
        "Designing for uncertainty in the UI",
        "Progressive disclosure of AI output",
        "Editability and user control",
        "Explaining what the AI did",
        "Handling failure gracefully",
        "Onboarding users to a fuzzy tool",
        "Measuring feature success",
        "Iterating with real usage data",
        "Knowing when to remove the AI",
    ]),
    ("Open source and self-hosting", [
        "Open weights vs open source",
        "Licence obligations",
        "Choosing an open model",
        "Hardware requirements by model size",
        "Serving with vLLM or TGI",
        "Fine-tuning your own",
        "Update and maintenance burden",
        "Cost comparison with APIs",
        "Data residency requirements",
        "Making the build-vs-buy call",
    ]),
    ("Multi-agent and orchestration", [
        "When one agent is not enough",
        "Orchestrator and worker patterns",
        "Parallel fan-out and synthesis",
        "Specialised agent roles",
        "Shared state and handoffs",
        "Cost multiplication risk",
        "Debugging multi-agent runs",
        "Deterministic orchestration code",
        "Evaluating a multi-agent system",
        "Simplifying back to one agent",
    ]),
    ("PROJECT: production RAG assistant", [
        "Goal: grounded answers over your own documents",
        "Ingestion and chunking pipeline",
        "Embedding and index construction",
        "Hybrid retrieval with reranking",
        "Grounded generation with citations",
        "Abstention when retrieval is weak",
        "Evaluation set and scoring harness",
        "Cost and latency measurement",
        "Prompt injection hardening",
        "Deploying it behind an API",
    ]),
])

# ---------------- Phase 9: Production AI (175-190) ----------------
add(175, [
    ("From notebook to software", [
        "Why notebooks do not ship",
        "Project structure for ML repos",
        "Configuration files over hard-coded values",
        "Separating data, training and serving code",
        "Logging instead of print",
        "Command-line entry points",
        "Packaging with pyproject.toml",
        "Dependency pinning",
        "Making the whole run one command",
        "Refactoring a notebook into modules",
    ]),
    ("Testing machine learning code", [
        "Unit tests for transforms",
        "Data schema tests",
        "Model contract tests: shape and range",
        "Behavioural tests for known cases",
        "Metamorphic testing",
        "Fixture datasets",
        "Testing training runs cheaply",
        "Golden-file tests for prompts",
        "Flaky tests from randomness",
        "A test suite you actually run",
    ]),
    ("Model serving", [
        "Batch vs online inference",
        "REST APIs with FastAPI",
        "Input validation with Pydantic",
        "Loading models at startup",
        "Concurrency and worker processes",
        "Request batching for GPUs",
        "Health and readiness endpoints",
        "Versioned endpoints",
        "Graceful shutdown",
        "Load testing your endpoint",
    ]),
    ("Containers and deployment", [
        "Dockerising an ML service",
        "Layer caching for fast builds",
        "Slim base images",
        "Handling large model artefacts",
        "Environment variables and secrets",
        "docker compose for local stacks",
        "Kubernetes concepts for ML",
        "Autoscaling considerations",
        "GPU scheduling",
        "Deploying to a cloud runtime",
    ]),
    ("CI/CD for ML", [
        "Continuous integration basics",
        "Linting and formatting gates",
        "Running tests on every push",
        "Training in CI: when it makes sense",
        "Evaluation gates before deploy",
        "Model registry promotion",
        "Blue-green and canary deploys",
        "Rollback plans",
        "GitHub Actions workflows",
        "A pipeline that blocks bad models",
    ]),
    ("Experiment tracking and reproducibility", [
        "What to record for every run",
        "MLflow and alternatives",
        "Artefact storage",
        "Data versioning with DVC",
        "Seeding everything",
        "Environment capture",
        "Comparing runs",
        "Linking a production model to its run",
        "Reproducing a six-month-old result",
        "A tracking habit that costs 5 minutes",
    ]),
    ("Feature stores and data infrastructure", [
        "Training/serving skew",
        "The feature store idea",
        "Offline vs online stores",
        "Point-in-time correct joins",
        "Feature freshness",
        "Shared features across teams",
        "When a feature store is overkill",
        "Simple alternatives that work",
        "Data contracts between teams",
        "Designing for consistency",
    ]),
    ("Monitoring models in production", [
        "The three things to monitor",
        "Input data drift",
        "Prediction drift",
        "Ground truth lag",
        "Population Stability Index",
        "Performance monitoring when labels arrive",
        "Segment-level monitoring",
        "Alert thresholds without fatigue",
        "Automated retraining triggers",
        "An on-call runbook for a model",
    ]),
    ("Incident response for AI systems", [
        "What a model incident looks like",
        "Detection and paging",
        "Immediate mitigation: rollback or disable",
        "Root cause categories",
        "Data pipeline failures",
        "Silent quality degradation",
        "Communication with stakeholders",
        "Postmortems without blame",
        "Turning incidents into tests",
        "Reducing mean time to recovery",
    ]),
    ("Scaling training", [
        "When single-GPU stops working",
        "Data parallelism",
        "Distributed data parallel",
        "Gradient accumulation",
        "Model parallelism and sharding",
        "ZeRO and FSDP",
        "Mixed precision at scale",
        "Checkpointing large runs",
        "Cluster cost management",
        "Deciding whether you need any of this",
    ]),
    ("Data engineering for AI", [
        "Batch vs streaming ingestion",
        "ETL and ELT patterns",
        "Orchestration with Airflow or Prefect",
        "Idempotent pipeline design",
        "Partitioning and file formats",
        "Data lake vs warehouse",
        "Incremental processing",
        "Backfills without breaking things",
        "Data quality monitoring",
        "Cost of storage and compute",
    ]),
    ("Privacy, security and compliance", [
        "PII identification and handling",
        "Anonymisation and pseudonymisation",
        "Differential privacy basics",
        "Federated learning",
        "Data retention policies",
        "GDPR and DPDP obligations",
        "Model inversion and membership inference",
        "Secrets management",
        "Audit trails",
        "Working with a compliance team",
    ]),
    ("Responsible AI in practice", [
        "Harms taxonomy for your product",
        "Measuring performance by subgroup",
        "Fairness definitions and their conflicts",
        "Mitigation at data, model and threshold level",
        "Transparency and model cards",
        "Human oversight requirements",
        "Contestability and appeals",
        "Environmental cost",
        "Documentation as accountability",
        "Saying no to a bad use case",
    ]),
    ("AI system architecture", [
        "Components of a production AI system",
        "Synchronous vs asynchronous flows",
        "Queues and workers",
        "Caching layers",
        "Fallback and degradation paths",
        "Multi-region considerations",
        "Vendor lock-in and abstraction layers",
        "Build vs buy per component",
        "Cost architecture",
        "Drawing your system on one page",
    ]),
    ("Working on an AI team", [
        "Roles: research, ML engineer, data engineer, product",
        "Writing a design doc",
        "Estimating ML work honestly",
        "Communicating uncertainty to stakeholders",
        "Code review for ML",
        "Sharing datasets and models internally",
        "Documentation that survives handover",
        "Managing expectations about AI",
        "Prioritising with limited compute",
        "Making a research result shippable",
    ]),
    ("PROJECT: deploy and operate a model", [
        "Goal: a model running in production with monitoring",
        "Packaging the trained pipeline",
        "FastAPI service with validation",
        "Dockerfile and local stack",
        "CI with tests and an eval gate",
        "Deployment to a host",
        "Structured request/response logging",
        "Drift monitoring job",
        "Alerting and a runbook",
        "Load test and cost report",
    ]),
])

# ---------------- Phase 10: Capstones and career (191-200) ----------------
add(191, [
    ("Choosing a capstone", [
        "Picking a problem you care about",
        "Scoping to four weeks of evenings",
        "Data availability check first",
        "Defining success before starting",
        "Baseline you must beat",
        "Risk list and mitigations",
        "Milestones and a thin first slice",
        "What makes a portfolio project credible",
        "Avoiding the tutorial-clone trap",
        "Writing the project brief",
    ]),
    ("CAPSTONE 1: predictive system", [
        "Problem framing and metric",
        "Data acquisition and validation",
        "EDA and leakage audit",
        "Baseline and iteration log",
        "Model selection with honest CV",
        "Error analysis and targeted improvement",
        "Calibration and threshold choice",
        "Packaging and serving",
        "Monitoring plan",
        "Write-up with results and limitations",
    ]),
    ("CAPSTONE 2: LLM application", [
        "Choosing a task LLMs genuinely help with",
        "Prompt design and versioning",
        "Retrieval or tools as needed",
        "Structured output and validation",
        "Golden eval set from real inputs",
        "Cost and latency budget",
        "Prompt injection hardening",
        "User interface for uncertainty",
        "Deployment and observability",
        "Demo video and documentation",
    ]),
    ("CAPSTONE 3: research replication", [
        "Choosing a paper with released code or clear method",
        "Reading it with the three-pass method",
        "Restating the core idea in one paragraph",
        "Minimal reimplementation",
        "Reproducing the headline number",
        "Where your numbers differ and why",
        "Ablating the key component",
        "Extending it by one small idea",
        "Documenting honestly, including failures",
        "Publishing the repository",
    ]),
    ("Writing about your work", [
        "Structure of a good technical write-up",
        "Leading with the result",
        "Explaining the method without jargon",
        "Charts that carry the argument",
        "Reporting limitations builds trust",
        "Reproducibility section",
        "README as the front door",
        "Blog post vs repository documentation",
        "Getting feedback before publishing",
        "Publishing on GitHub Pages",
    ]),
    ("Reading research", [
        "Where papers appear: arXiv and conferences",
        "The three-pass reading method",
        "Distinguishing contribution from packaging",
        "Reading the limitations section first",
        "Checking baselines for fairness",
        "Reproducibility red flags",
        "Following citation trails",
        "Keeping a paper notebook",
        "Implementing one idea per month",
        "Staying current without drowning",
    ]),
    ("The AI job landscape", [
        "Research scientist vs ML engineer vs data scientist",
        "AI engineer and the LLM application role",
        "Data engineer and platform roles",
        "What each role actually does daily",
        "Skills that transfer between them",
        "Domain specialisation as leverage",
        "Startup vs enterprise trade-offs",
        "Building a portfolio for a target role",
        "Open source contributions",
        "Choosing your next two years",
    ]),
    ("Interview preparation", [
        "ML fundamentals questions",
        "Coding rounds and what they test",
        "Case study and system design rounds",
        "Explaining your projects clearly",
        "Handling 'why did you choose that' questions",
        "Discussing failures well",
        "Statistics and probability questions",
        "Take-home assignments",
        "Questions you should ask them",
        "A four-week preparation plan",
    ]),
    ("Continuous learning system", [
        "Choosing sources worth your attention",
        "A weekly learning cadence",
        "Learning by building, not watching",
        "Spaced repetition for fundamentals",
        "Teaching to test understanding",
        "Communities worth joining",
        "Tracking what you learned",
        "Avoiding tutorial hell",
        "Depth-first on one area per quarter",
        "Your personal curriculum for year two",
    ]),
    ("Day 200: the road ahead", [
        "What 200 days actually gave you",
        "Auditing your own gaps honestly",
        "The fundamentals that will not expire",
        "The tools that will expire",
        "Choosing a specialisation",
        "Building in public",
        "Contributing to open source AI",
        "Mentoring someone behind you",
        "Ethics as an ongoing practice",
        "Your next 200 days",
    ]),
])


def _self_check() -> None:
    days = [d for d, _, _ in CURRICULUM]
    assert days == list(range(1, 201)), f"expected days 1..200, got {days[0]}..{days[-1]} ({len(days)} entries)"
    assert len(set(days)) == 200
    for day, theme, concepts in CURRICULUM:
        assert len(concepts) == 10, (day, theme)
        assert len(set(concepts)) == 10, f"Day {day}: duplicate concept titles"
    print(f"curriculum ok — {len(CURRICULUM)} days, {sum(len(c) for _, _, c in CURRICULUM)} concepts")


if __name__ == "__main__":
    _self_check()
